[project]
name = "pacwomen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mazegenerator",
    "pydantic>=2.13.5",
    "pygame-ce>=2.5.8",
]

[tool.uv.sources]
mazegenerator = { path = "mazegenerator-2.0.2-py3-none-any.whl" }
